FROM ubuntu:latest

RUN apt-get update && apt-get install -y nodejs npm

WORKDIR /voting-contract

RUN rm -rf ./*

COPY package*.json /voting-contract/

RUN npm install

COPY src /voting-contract/src/

RUN npm run buildLinux
